name: CD

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build it
      run: yarn build
      
  deploy:
    runs-on: ubuntu-latest
    
    needs: build

    env:
      ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}

    steps:
    - name: Deploy it!
      run: >
        now deploy
        --local-config=./now.json
        --no-clipboard
        --token ${ZEIT_TOKEN}
